apiVersion: v1
kind: Service
metadata:
  name: devops-api-service
  namespace: devops-demo

spec:
  type: NodePort

  selector:
    app: devops-api

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
